name: Build Hospital client pc

on:
  push:

jobs:
  package-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
          channel: 'stable'
      - run: flutter --version

      - name: Build
        run: |
          python build.py

      - name: Rename
        shell: bash
        run: |
          mv Output/setup.exe ./hospital-client-pc-installer-x86_64.exe
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./*.exe"
          bodyFile: "body.md"
