name: Build Hospital client pc

on:
  push:
  workflow_dispatch:

env:
  VERSION: 1.1.0

jobs:
  package-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          pushd ..
          git clone https://github.com/Kingtous/media-kit.git --depth=1
          popd

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'
          channel: 'stable'
      - run: flutter --version

      - name: Build
        run: |
          python build.py

      - name: Rename
        shell: bash
        run: |
          mv Output/setup.exe ./hospital-client-pc-installer-x86_64.exe
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          artifacts: "./*.exe"
          bodyFile: "body.md"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
